# Generated by Django 2.2.5 on 2021-10-12 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211012_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favs',
        ),
    ]
